### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode characters in position 3-4

### ISSUE THREAD

**Issue by lynnux** [MisterBianco/wifijammer-ng#8]
```
[*] 38:d5:47:0b:b3:0c    - 6     - ASUS                      - 0
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "wifijammer-ng.py", line 160, in channel_hop
    self.output()
  File "wifijammer-ng.py", line 225, in output
    str(len([x[0] for x in self.clients if x[0].lower() == ap[0].lower()]))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 3-4: ordinal not in range(128)
```

I'm in china there maybe has some chinese chars in ap name. Well, the original wifijammer doesn't has the trouble.

**Comment by MisterBianco** [comment]
This issue is usually due to a unicode character in the access points ssid. Some millenial assholes like putting shit emojis in their SSID's and messing up these scanners. It requires an additional filter and is a pain in the ass.
